#!/usr/bin/env bash

source ~/.cache/wal/colors.sh

export fg_a="#FF${foreground/'#'}"
export main_bg="#D0${color0/'#'}"

res_w=$(xrandr | grep "current" | awk '{print $8a}')

WIDTH=$res_w # bar width
HEIGHT=18 # bar height
XOFF=0 # x offset
YOFF=0 # y offset

BBG=$main_bg # bar background color
BFG=$fg_a

# Sleep constants
MUSIC_SLEEP=3
UPDATE_SLEEP=60
WORKSPACE_SLEEP=0.3
DATE_SLEEP=1
VOLUME_SLEEP=1

#                  
icon_cpu=""
icon_mem=""
icon_vol=""
icon_vol_mute=""
icon_music=""
icon_update=""
icon_pacman=""
icon_space=""

PANEL_FIFO=/tmp/panel-fifo
FONT1="Inconsolata for Powerline:size=12"
ICONFONT="FontAwesome:size=11"
GEOMETRY="${WIDTH}x${HEIGHT}+${XOFF}+${YOFF}"
