#!/bin/bash

echo "Starting to mount network drives"

echo "Resetting mounts"
fusermount -uz ~/Videos
# fusermount -uz ~/Projects
fusermount -uz ~/Music
fusermount -uz ~/Pictures
# fusermount -uz ~/Documents
fusermount -uz /media/shaine/geshtinanna
# umount /media/shaine/geshtinanna

echo "Mounting geshtinanna"
sshfs -o reconnect geshtinanna: /media/shaine/geshtinanna

# echo "Mounting Documents"
# bindfs /media/shaine/geshtinanna/documents ~/Documents

echo "Mounting Pictures"
bindfs /media/shaine/geshtinanna/images ~/Pictures

echo "Mounting Music"
bindfs /media/shaine/geshtinanna/music ~/Music

# echo "Mounting Projects"
# bindfs /media/shaine/geshtinanna/projects ~/Projects

echo "Mounting Video"
bindfs /media/shaine/geshtinanna/video ~/Videos
