#!/bin/bash

echo "Starting to mount network drives"

sshfs geshtinanna: /media/shaine/geshtinanna

bindfs /media/shaine/geshtinanna/documents Documents
bindfs /media/shaine/geshtinanna/images Pictures
bindfs /media/shaine/geshtinanna/music Music
bindfs /media/shaine/geshtinanna/projects Projects
bindfs /media/shaine/geshtinanna/video Video
